;;; ============================================================
;;; ASCII Code Points (also used as key codes)
;;; ============================================================

ASCII_BELL      = $07           ; bell
ASCII_LEFT      = $08           ; left arrow
ASCII_TAB       = $09           ; tab
ASCII_DOWN      = $0A           ; down arrow
ASCII_UP        = $0B           ; up arrow
ASCII_CR        = $0D           ; carriage return
ASCII_RIGHT     = $15           ; right arrow
ASCII_SYN       = $16           ; scroll text window up
ASCII_ETB       = $17           ; scroll text window down
ASCII_CLEAR     = $18           ; clear
ASCII_EM        = $19           ; move cursor to upper left
ASCII_ESCAPE    = $1B           ; escape
ASCII_DELETE    = $7F           ; delete
